version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: python:3.10-slim
    restart: unless-stopped
    depends_on:
      - mongo
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/silo
      - JWT_SECRET=devsecret
      - INIT_ADMIN_SECRET=devseed
    command: bash -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

  frontend:
    image: node:18
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend/vite-react:/app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"

volumes:
  mongo-data:
